Pembekalan_Net/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Pembekalan_Net.DataModel;
using Pembekalan_Net.Services;
using Pembekalan_Net.ViewModel;

namespace Pembekalan_Net.Controllers
{
    public class RoleController : Controller
    {
        //private readonly NewNetContext db;
        private readonly RoleServices roleService;

        public RoleController(RoleServices _roleServices)
        {
            //db = _db;
            roleService = _roleServices;
        }

        public IActionResult Index()
        {
            List<VMTblRole> dataView = roleService.GetAllData();
            ViewBag.listRole = dataView;
            return View(dataView);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(VMTblRole dataView)
        {
            VMResponse response = new VMResponse();

            if (ModelState.IsValid)
            {
                response = roleService.Create(dataView);

                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            response.Entity = dataView;
            return View(response.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblRole dataView)
        {
            VMResponse response = new VMResponse();

            if (ModelState.IsValid)
            {
                response = roleService.Edit(dataView);

                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            response.Entity = dataView;
            return View(response.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }
        public IActionResult Delete(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public VMResponse DeleteRole(int id)
        {
            VMResponse response = new VMResponse();

            response = roleService.Delete(id);
            return response;
        }

        //DELETE DENGAN CARA KEDUA
        //[HttpPost]
        //public IActionResult Delete(VMTblRole dataView)
        //{
        //    VMResponse response = new VMResponse();

        //    response = roleService.Edit(dataView);

        //    if (response.Success)
        //    {
        //        return RedirectToAction("Index");
        //    }
            
        //    response.Entity = dataView;
        //    return View(response.Entity);
        //}
    }
}

Pembekalan_Net/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pembekalan_Net</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pembekalan_Net.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pembekalan_Net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Pembekalan_Net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
                @* <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> *@
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pembekalan_Net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pembekalan_Net</title>
    @* Jquery *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pembekalan_Net.styles.css" asp-append-version="true" />

    @* Template Bootstrap AdminMart *@
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!-- Custom CSS -->
    <link href="../assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="../assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="../assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="../dist/css/style.min.css" rel="stylesheet">


    @* SweetAlert *@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/plugins/SweetAlert2.js"></script>
    <script src="sweetalert2.min.js"></script>
    <link rel="stylesheet" href="sweetalert2.min.css">

    @* Toastr *@
    <script src="~/plugins/toastr/Toastr.min.js"></script>
    <link rel="stylesheet" href="~/plugins/toastr/Toastr.css">

</head>
<body>

    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
         <partial name="_Header" />
         <partial name="_Sidebar" />

        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <footer class="footer text-center text-muted">
                Project By Eliza. 
                All Rights Reserved by Adminmart. Designed and Developed by <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>
        </div>

    </div>

  

    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
                @* <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> *@
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- All Jquery -->
    <!-- ============================================================== -->
    
    <script src="../assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="../assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="../dist/js/app-style-switcher.js"></script>
    <script src="../dist/js/feather.min.js"></script>
    <script src="../assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="../dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="../dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="../assets/extra-libs/c3/d3.min.js"></script>
    <script src="../assets/extra-libs/c3/c3.min.js"></script>
    <script src="../assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="../assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="../assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="../assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="../dist/js/pages/dashboards/dashboard1.min.js"></script>
</body>
</html>

Pembekalan_Net/Views/Shared/_Sidebar.cshtml
@using Pembekalan_Net.Services
@inject AuthServices authServices
@{
    int IdCustomer = @Context.Session.GetInt32("idCustomer") ?? 0;
    string nameCustomer = @Context.Session.GetString("nameCustomer") ?? "";
    int idRole = @Context.Session.GetInt32("idRole") ?? 0;

    var menuAccess = await authServices.MenuAccess(idRole);
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                @if(idRole != 0)
                {
                    @foreach (var parent in menuAccess)
                    {
                        <li class="sidebar-item" >
                            <a class="sidebar-link has-arrow" href="javascript:void(0)"
                               aria-expanded="false">
                                <i data-feather="@parent.MenuIcon" class="feather-icon"></i><span class="hide-menu">@parent.MenuName </span>
                            </a>
                            <ul aria-expanded="false" class="collapse  first-level base-level-line">
                                @foreach (var child in parent.ListChild)
                                {
                                <li class="sidebar-item">
                                    <a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="sidebar-link">
                                        <i data-feather="@child.MenuIcon" class="feather-icon"></i>
                                        <span class="hide-menu">
                                            @child.MenuName
                                        </span>
                                    </a>
                                </li>
                                }
                            </ul>
                        </li>

                        <li class="mb-4"></li>
                    }
                }
                else
                {
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-area="" asp-controller="Home" asp-action="Index"
                           aria-expanded="false">
                            <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Home</span>
                        </a>
                    </li>
                    <li class="list-divider"></li>
                    <li class="sidebar-item">
                        <button class="sidebar-link btn w-100" id="btn-login" type="button"
                           aria-expanded="false">
                            <i data-feather="log-in" class="feather-icon"></i><span class="hide-menu">Login</span>
                        </button>
                    </li>
                }

                
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<script>
    $("#btn-login").click(function (event) {
        // location.replace("/Auth/Login");
        $("#modal_body").empty()
        $(".modal-dialog").addClass("modal-xl");
        $("#modal_body").load("/Auth/Login")
        $("#my_modal").modal("show")
    })
</script>